name: xeus-calc
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - xeus-zmq=3.1.0
  - nlohmann_json 
  - cppzmq
  - xtl=0.7.3
