parameters:
  - name: 'platform'
    type: string

steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate xeus-calc
      conda install gxx_linux-64 libcxx -c conda-forge
    condition: eq('${{ parameters.platform }}', 'Linux')
    displayName: Install conda-forge compilers

  - script: |
      source activate xeus-calc
      mkdir build
      cd build
      cmake -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DDOWNLOAD_GTEST=ON -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX $(Build.SourcesDirectory)
    displayName: Configure xeus-calc
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate xeus-calc
      make install -j2
    displayName: Build xeus-calc
    workingDirectory: $(Build.BinariesDirectory)/build

  - script: |
      source activate xeus-calc
      ./test_xeus_calc
    displayName: Test xeus-calc (C++)
    workingDirectory: $(Build.BinariesDirectory)/build/test
